services:

  frontend:
    build:
      context: ../../../frontend
      dockerfile: Dockerfile.dev
    image: ${FRONTEND_IMAGE}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ../../../frontend:/app
      - ../../../contracts/api.yaml:/app/contracts/api.yaml:ro
      - /app/node_modules

  scripts:
    build:
      context: ../../../scripts
      dockerfile: Dockerfile.dev
    image: ${SCRIPTS_IMAGE}
    volumes:
      - ../../../scripts:/app
      - ../../../contracts:/app/contracts:ro
      - ../../../backend:/app/backend
      - ../../../frontend:/app/frontend
