# Imagen base fija
FROM python:3.12-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar solo requirements para aprovechar cache
COPY requirements-base.txt /app/
COPY requirements-dev.txt /app/

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*


# Instalar dependencias de Python
RUN pip install --upgrade pip && \
    pip install -r requirements-dev.txt

# Copiar todo el código del backend
COPY . /app

# Variable de entorno para usar configuración de desarrollo
ENV DJANGO_SETTINGS_MODULE=config.settings.development

# Comando por defecto para desarrollo
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
